### ISSUE TITLE
Duplicated JARs with different organizations

### ISSUE THREAD

**Issue by alexarchambault** [xerial/sbt-pack#58]
For now, JARs can be considered duplicates of each other only if they have the same organization, but they sometimes don't.

For example, if one uses a library that relies on akka (organization `com.typesafe.akka`) and uses spark at the same time, which relies on its own version of akka (organization `org.spark-project.akka`), one runs into conflicts because both versions land in `lib`:
```
akka-actor_2.10-2.2.0.jar // from com.typesafe.akka
akka-actor_2.10-2.2.3-shaded-protobuf.jar // from org.spark-project.akka
```

Shouldn't the organization be ignored when looking for duplicate JARs?

Maybe loosely related to https://github.com/xerial/sbt-pack/issues/27

**Comment by xerial** [comment]
If you know which jar should be removed from `lib`, how about adding `ExclusionRule` to the dependency list? http://www.scala-sbt.org/0.13.5/docs/Detailed-Topics/Library-Management.html#exclude-transitive-dependencies

Generally speaking, ignoring the organization name is not recommended since it might include customized built of the same-name projects. And also in your case, the artifact types (jar and shared jar) are different, so detecting these jars as duplicate is a little bit difficult.

**Comment by alexarchambault** [comment]
Ok, I can understand. I can't get exclusion rules to work in my use case (to be excluded dependency - akka - is added by a sbt plugin - play), but I think I should be able to find another way to get what I want. Thanks.
